/**
 * Datos de razas de perros.
 * Cada raza contiene información básica como nombre, tamaño, carácter, promedio de vida y una URL de imagen.
 */

export const datosRazas = [
    { id: 1, nombre: "Affenpinscher", tamano: "pequeño", caracter: "vivo", promedioVida: "12 años", imagen: "" },
    { id: 2, nombre: "African", tamano: "mediano", caracter: "independiente", promedioVida: "10-15 años", imagen: "" },
    { id: 3, nombre: "Airedale", tamano: "grande", caracter: "inteligente", promedioVida: "10-14 años", imagen: "" },
    { id: 4, nombre: "Akita", tamano: "grande", caracter: "leal", promedioVida: "10-15 años", imagen: "" },
    { id: 5, nombre: "Appenzeller", tamano: "mediano", caracter: "enérgico", promedioVida: "12-14 años", imagen: "" },
    { id: 6, nombre: "Australian Kelpie", tamano: "mediano", caracter: "inteligente", promedioVida: "12-15 años", imagen: "" },
    { id: 7, nombre: "Australian Shepherd", tamano: "mediano", caracter: "activo", promedioVida: "12-15 años", imagen: "" },
    { id: 8, nombre: "Bakharwal", tamano: "grande", caracter: "protector", promedioVida: "10-12 años", imagen: "" },
    { id: 9, nombre: "Basenji", tamano: "pequeño", caracter: "independiente", promedioVida: "12-16 años", imagen: "" },
    { id: 10, nombre: "Beagle", tamano: "pequeño", caracter: "amigable", promedioVida: "10-15 años", imagen: "" },
    { id: 11, nombre: "Bluetick", tamano: "mediano", caracter: "resistente", promedioVida: "12-14 años", imagen: "" },
    { id: 12, nombre: "Borzoi", tamano: "grande", caracter: "gentil", promedioVida: "10-12 años", imagen: "" },
    { id: 13, nombre: "Bouvier", tamano: "grande", caracter: "firme", promedioVida: "10-12 años", imagen: "" },
    { id: 14, nombre: "Boxer", tamano: "grande", caracter: "juguetón", promedioVida: "10-12 años", imagen: "" },
    { id: 15, nombre: "Brabancon", tamano: "pequeño", caracter: "vivo", promedioVida: "12-15 años", imagen: "" },
    { id: 16, nombre: "Briard", tamano: "grande", caracter: "leal", promedioVida: "10-12 años", imagen: "" },
    { id: 17, nombre: "Buhund Noruego", tamano: "mediano", caracter: "amigable", promedioVida: "12-16 años", imagen: "" },
    { id: 18, nombre: "Bulldog Boston", tamano: "pequeño", caracter: "afectuoso", promedioVida: "10-15 años", imagen: "" },
    { id: 19, nombre: "Bulldog Inglés", tamano: "mediano", caracter: "calmo", promedioVida: "8-10 años", imagen: "" },
    { id: 20, nombre: "Bulldog Francés", tamano: "pequeño", caracter: "afectuoso", promedioVida: "10-14 años", imagen: "" },
    { id: 21, nombre: "Bullterrier Staffordshire", tamano: "mediano", caracter: "valiente", promedioVida: "12-16 años", imagen: "" },
    { id: 22, nombre: "Cattledog Australiano", tamano: "mediano", caracter: "inteligente", promedioVida: "12-15 años", imagen: "" },
    { id: 23, nombre: "Cavapoo", tamano: "pequeño", caracter: "amigable", promedioVida: "10-15 años", imagen: "" },
    { id: 24, nombre: "Chihuahua", tamano: "pequeño", caracter: "valiente", promedioVida: "12-20 años", imagen: "" },
    { id: 25, nombre: "Chippiparai", tamano: "mediano", caracter: "rápido", promedioVida: "12-15 años", imagen: "" },
    { id: 26, nombre: "Chow", tamano: "grande", caracter: "independiente", promedioVida: "10-15 años", imagen: "" },
    { id: 27, nombre: "Clumber", tamano: "grande", caracter: "tranquilo", promedioVida: "10-12 años", imagen: "" },
    { id: 28, nombre: "Cockapoo", tamano: "pequeño", caracter: "amigable", promedioVida: "12-15 años", imagen: "" },
    { id: 29, nombre: "Collie", tamano: "grande", caracter: "inteligente", promedioVida: "12-15 años", imagen: "" },
    { id: 30, nombre: "Coonhound", tamano: "grande", caracter: "valiente", promedioVida: "10-12 años", imagen: "" },
    { id: 31, nombre: "Corgi Cardigan", tamano: "pequeño", caracter: "juguetón", promedioVida: "12-15 años", imagen: "" },
    { id: 32, nombre: "Cotón de Tulear", tamano: "pequeño", caracter: "afectuoso", promedioVida: "14-16 años", imagen: "" },
    { id: 33, nombre: "Dachshund", tamano: "pequeño", caracter: "valiente", promedioVida: "12-16 años", imagen: "" },
    { id: 34, nombre: "Dalmata", tamano: "grande", caracter: "activo", promedioVida: "10-13 años", imagen: "" },
    { id: 35, nombre: "Gran Danés", tamano: "grande", caracter: "gentil", promedioVida: "7-10 años", imagen: "" },
    { id: 36, nombre: "Danish Swedish", tamano: "mediano", caracter: "inteligente", promedioVida: "10-14 años", imagen: "" },
    { id: 37, nombre: "Deerhound Escocés", tamano: "grande", caracter: "gentil", promedioVida: "10-12 años", imagen: "" },
    { id: 38, nombre: "Dhole", tamano: "mediano", caracter: "social", promedioVida: "10-15 años", imagen: "" },
    { id: 39, nombre: "Dingo", tamano: "mediano", caracter: "independiente", promedioVida: "10-15 años", imagen: "" },
    { id: 40, nombre: "Doberman", tamano: "grande", caracter: "inteligente", promedioVida: "10-14 años", imagen: "" },
    { id: 41, nombre: "Elkhound Noruego", tamano: "grande", caracter: "protector", promedioVida: "10-14 años", imagen: "" },
    { id: 42, nombre: "Entlebucher", tamano: "mediano", caracter: "energético", promedioVida: "12-15 años", imagen: "" },
    { id: 43, nombre: "Eskimo", tamano: "mediano", caracter: "afectuoso", promedioVida: "10-12 años", imagen: "" },
    { id: 44, nombre: "Lapphund Finés", tamano: "grande", caracter: "amigable", promedioVida: "12-15 años", imagen: "" },
    { id: 45, nombre: "Bichón Frisé", tamano: "pequeño", caracter: "juguetón", promedioVida: "12-15 años", imagen: "" },
    { id: 46, nombre: "Gaddi", tamano: "grande", caracter: "protector", promedioVida: "10-12 años", imagen: "" },
    { id: 47, nombre: "Pastor Alemán", tamano: "grande", caracter: "inteligente", promedioVida: "9-13 años", imagen: "" },
    { id: 48, nombre: "Greyhound Indio", tamano: "grande", caracter: "rápido", promedioVida: "10-14 años", imagen: "" },
    { id: 49, nombre: "Greyhound Italiano", tamano: "grande", caracter: "rápido", promedioVida: "10-14 años", imagen: "" },
    { id: 50, nombre: "Hound Coon", tamano: "mediano", caracter: "valiente", promedioVida: "12-14 años", imagen: "" },
    { id: 51, nombre: "Husky Siberiano", tamano: "grande", caracter: "juguetón", promedioVida: "10-15 años", imagen: "" },
    { id: 52, nombre: "Labrador Retriever", tamano: "grande", caracter: "afectuoso", promedioVida: "10-12 años", imagen: "" },
    { id: 53, nombre: "Mastín", tamano: "grande", caracter: "leal", promedioVida: "8-10 años", imagen: "" },
    { id: 54, nombre: "Maltés", tamano: "pequeño", caracter: "amigable", promedioVida: "12-15 años", imagen: "" },
    { id: 55, nombre: "Pomerania", tamano: "pequeño", caracter: "juguetón", promedioVida: "12-16 años", imagen: "" },
    { id: 56, nombre: "Pug", tamano: "pequeño", caracter: "afectuoso", promedioVida: "12-15 años", imagen: "" },
    { id: 57, nombre: "Rottweiler", tamano: "grande", caracter: "firme", promedioVida: "8-10 años", imagen: "" },
    { id: 58, nombre: "Saluki", tamano: "grande", caracter: "independiente", promedioVida: "12-14 años", imagen: "" },
    { id: 59, nombre: "San Bernardo", tamano: "grande", caracter: "gentil", promedioVida: "8-10 años", imagen: "" },
    { id: 60, nombre: "Schnauzer", tamano: "mediano", caracter: "inteligente", promedioVida: "12-15 años", imagen: "" },
    { id: 61, nombre: "Setter Irlandés", tamano: "grande", caracter: "amigable", promedioVida: "12-15 años", imagen: "" },
    { id: 62, nombre: "Shiba Inu", tamano: "mediano", caracter: "independiente", promedioVida: "12-15 años", imagen: "" },
    { id: 63, nombre: "Shih Tzu", tamano: "pequeño", caracter: "afectuoso", promedioVida: "10-16 años", imagen: "" },
    { id: 64, nombre: "Tibetano", tamano: "grande", caracter: "valiente", promedioVida: "10-12 años", imagen: "" },
    { id: 65, nombre: "Terranova", tamano: "grande", caracter: "gentil", promedioVida: "10-12 años", imagen: "" },
    { id: 66, nombre: "Vizsla", tamano: "grande", caracter: "afectuoso", promedioVida: "10-14 años", imagen: "" },
    { id: 67, nombre: "Whippet", tamano: "mediano", caracter: "rápido", promedioVida: "12-15 años", imagen: "" },
    { id: 68, nombre: "Xoloitzcuintli", tamano: "mediano", caracter: "independiente", promedioVida: "10-14 años", imagen: "" }
  ];
  export const razas = []; // Solo como ejemplo

export function imprimirRazas() {
  console.log(datosRazas);
}